### ISSUE TITLE
Missing Arcade Module and Latch blocks

### ISSUE THREAD

**Issue by audreybartlett** [mathworks-robotics/robotics-playground#1]
We noticed that the "Arcade Module" and "Latch" blocks which were in 20.1.2 are no longer in the Utilities library in release 20.1.4. Will they be re-added in future releases or is there another way we can add them to the library?

**Comment by javendanoarb** [comment]
@audreybartlett  thanks for reporting it! We have updated the release and the blocks should be there now. You can copy the library from [here](https://github.com/mathworks-robotics/robotics-playground/blob/master/lib/RoboticsPlayground.slx) or uninstall/reinstall the toolbox in MATLAB.
