### ISSUE TITLE
Error Message When Using Distance Sensor Block

### ISSUE THREAD

**Issue by bentay85** [mathworks-robotics/robotics-playground#2]
I'm on Matlab R2020b. I am able to run the obstacle environment with 2 motors. 

However, when I included a Distance Sensor Block into the Simulink model, I get the following error:

MATLAB System block 'wosRobotSim/Distance Sensor/MATLAB System' error occurred when invoking 'setupImpl' method of 'LidarSensorRP'. The error was thrown from '
 'C:\Users\benja\AppData\Roaming\MathWorks\MATLAB Add-Ons\Toolboxes\Robotics Playground\lib\Resources\Utils\createMapFromName.m' at line 48
 'C:\Users\benja\AppData\Roaming\MathWorks\MATLAB Add-Ons\Toolboxes\Robotics Playground\lib\Resources\Utils\createMapFromName.m' at line 37
 'C:\Users\benja\AppData\Roaming\MathWorks\MATLAB Add-Ons\Toolboxes\Robotics Playground\lib\Resources\Utils\LidarSensorRP.m' at line 34'.
Caused by:
Unable to resolve the name robotics.OccupancyGrid.

**Comment by javendanoarb** [comment]
This error occurs when Navigation Toolbox is not installed in MATLAB. There is an issue with the stated dependencies for the Robotics Playground toolbox. We will update it, thanks for pointing it out.

**Comment by bentay85** [comment]
Thanks for the response. I have tested with the navigation toolbox installed and it is working now.
